services:
  - type: web
    name: esex-portal
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18